### ISSUE TITLE
TypeError when running mesh_object (python unicode vs std::string)

### ISSUE THREAD

**Issue by pgorczak** [wg-perception/reconstruction#1]
The error occurs when the [ecto.Dealer gets instantiated](../blob/master/apps/mesh_object#L86).
The exact type error message is

> No registered converter was able to produce a C++ rvalue of type std::string from this Python object of type unicode

It seems that a _str_ type is expected here instead of _unicode_ by the Python wrapper.
Running `object_search.py` from [object_recognition_core](../../object_recognition_core/blob/master/apps/dbscripts/object_search.py) indeed prints a list of _unicode_ elements in the `session ids` line but an _str_ in the `db id` line.

I don't know if this issue belongs to reconstruction or rather the core since it could already happen in the upload script. Please bear with me if this is the wrong place.

Forgot to mention: I am using the ROS Indigo packages on Ubuntu 14.04.

**Comment by corot** [comment]
@pgorczak, I'm getting the same error you reported. I use code from master branch on indigo. Did you solved the problem? Thanks!

**Comment by vrabaud** [comment]
which instruction are you running exactly ? Thx

**Comment by corot** [comment]
```
rosrun object_recognition_reconstruction mesh_object --all --visualize --commit
```

**Comment by corot** [comment]
btw, the first two *libGL error* lines are due to a problem with my graphics driver that I have already fixed.

**Comment by corot** [comment]
@vrabaud, I'm unable to find any solution for this... should I create a new issue with this?
